server:
  port: 20909
  servlet:
    context-path: /lineage
spring:
  application:
    name: data-lineage

  data:
    neo4j:
      username: neo4j
      password: password # 如果没有修改，默认密码为 neo4j
      uri: bolt://47.122.7.128:27687 # BOLT IPhttp://172.23.16.68:7474/
      auto-index: update

  kafka:
    bootstrap-servers: 47.122.7.128:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: sql-parser-group
      # 手动提交
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 60000
    listener:
      log-container-config: false
      concurrency: 5
      # 手动提交
      ack-mode: manual_immediate
      missing-topics-fatal: false

lineage:
  datasource:
    0_gp:
      jdbc-url: jdbc:postgresql://139.159.236.138:5432/pg-zhongtiejian?useUnicode=true&characterEncoding=utf-8&currentSchema=test
      username: postgres
      password: Zhongruan@2021
      driver-class-name: org.postgresql.Driver
