version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 本级内网ip
      KAFKA_CREATE_TOPICS: "lineage:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - $PWD/docker.sock:/var/run/docker.sock
      - $PWD/kafka:/kafka
  # kafka-manager:
  #   image: sheepkiller/kafka-manager
  #   environment:
  #       ZK_HOSTS: 10.211.55.2:2181
  #   ports:
  #     - "9000:9000"
